### ISSUE TITLE
Doesn't Works :(

### ISSUE THREAD

**Issue by ezar** [glitch452/MMM-LocalTemperature#1]
I don't know whats the problem :(
I add more logging to node_helper but I doesnt undertood.

Can you help me?

Server Log:
> 0|MagicMir | MMM-LocalTemperature: Socket Notification Received: "GET_DATA".
> 0|MagicMir | { "humidity": 25.0, "celcius": 16.0, "fahrenheit": 60.8, "kelvin": 289.1, "attempts": 2 }
> 0|MagicMir | { original: 
> 0|MagicMir |    { instanceID: 'module_10_MMM-LocalTemperature_20406556160670042',
> 0|MagicMir |      scriptPath: 'modules/MMM-LocalTemperature/DHT',
> 0|MagicMir |      sensorPin: 7,
> 0|MagicMir |      attemptNum: 1,
> 0|MagicMir |      notification: 'DATA_RECEIVED' },
> 0|MagicMir |   isSuccessful: true,
> 0|MagicMir |   data: 
> 0|MagicMir |    { humidity: 25,
> 0|MagicMir |      celcius: 16,
> 0|MagicMir |      fahrenheit: 60.8,
> 0|MagicMir |      kelvin: 289.1,
> 0|MagicMir |      attempts: 2 } }
> 0|MagicMir | DATA_RECEIVED

Chrome Log:
> MMM-LocalTemperature: Request sent to get the sensor data. 
> MMM-LocalTemperature.js:444 MMM-LocalTemperature: Sensor read Successful, data received from the sensor after 2 attempt(s). 
> module.js:154 clock received a module notification: INDOOR_TEMPERATURE from sender: MMM-LocalTemperature
> module.js:154 calendar received a module notification: INDOOR_TEMPERATURE from sender: MMM-LocalTemperature
> newsfeed.js:340 newsfeed - received notification: INDOOR_TEMPERATURE
> newsfeed.js:391 newsfeed - unknown notification, ignoring: INDOOR_TEMPERATURE
> module.js:154 MMM-Tools received a module notification: INDOOR_TEMPERATURE from sender: MMM-LocalTemperature
> module.js:154 clock received a module notification: INDOOR_HUMIDITY from sender: MMM-LocalTemperature
> module.js:154 calendar received a module notification: INDOOR_HUMIDITY from sender: MMM-LocalTemperature
> newsfeed.js:340 newsfeed - received notification: INDOOR_HUMIDITY
> newsfeed.js:391 newsfeed - unknown notification, ignoring: INDOOR_HUMIDITY
> module.js:154 MMM-Tools received a module notification: INDOOR_HUMIDITY from sender: MMM-LocalTemperature

**Comment by glitch452** [comment]
It looks like the data is being collected from the sensor successfully.  

If you are using the currentweather module to show the temperature and/or the humidity, then make sure you set "showIndoorTemperature: true" and/or "showIndoorHumidity: true" in the module configuration?  

If you are using this module to display the temperature and/or humidity, then make sure this module has a position set, and set the configuration option "showTemperature: true" and/or "showHumidity: true"

**Comment by ezar** [comment]
Thanks!!!!
