### ISSUE TITLE
DHT not pulling data

### ISSUE THREAD

**Issue by ladew222** [glitch452/MMM-LocalTemperature#12]
I had an issue with the temp not pulling. It works in python, but not from your DHT code.  I tried other C code and had issues until I did what is listed here [https://www.raspberrypi.org/forums/viewtopic.php?t=197331](https://www.raspberrypi.org/forums/viewtopic.php?t=197331)

I changed the 16 to 50. Then I would get readings every 3 or 4 calls as they indicated.

**Comment by Mike00001** [comment]
Hi @ladew222 ,

I seem to have the same problem but I'm not sure.

With a python script no problem reading information from the probe. Could you give more details on how you went about it? I am not familiar with C.

Have a great day! :)

**Comment by fortoszone** [comment]
@ladew222 add to config:

> showHumidity: "true",
> showTemperature: "true"

in case if u'r still on it and for my record lmao

**Comment by glitch452** [comment]
This might be the issue with using sudo on a pi4b with an older wiringpi version.  I'm updating the module today.  Please try the new version and let me know.
