### ISSUE TITLE
Square icon instead of the temperature icon

### ISSUE THREAD

**Issue by lunaticasylum** [glitch452/MMM-LocalTemperature#15]
Hi,

So happy, I finally managed to make it works. It took me a while....

The only thing is that the temperature icon is square. The humidity is fine.

Nothing to do with the line 330 apparently. Fa is fine.

Thanks for your help.

Yann

**Comment by hxreborn** [comment]
Hi there @lunaticasylum, to solve the issue you can add the new Font Awesome version in your custom.css

`@import url("https://use.fontawesome.com/releases/v5.3.1/css/all.css");`

**Comment by lunaticasylum** [comment]
HI Rafagale,

Thanks a lot. Il will try tonight.

Yann

**Comment by lunaticasylum** [comment]
Hi Rafagale,
 
I hope you are fine. Sorry to bother you but where do I find the custom.css ?
 
Thanks for your help
 
Cheers
 
Yann
 
 
 
 
> Message du 28/03/21 20:39
> De : "rafagale" 
> A : "glitch452/MMM-LocalTemperature" 
> Copie à : "lunaticasylum" , "Mention" 
> Objet : Re: [glitch452/MMM-LocalTemperature] Square icon instead of the temperature icon (#15)
> 
>
>
> Hi there @lunaticasylum, to solve the issue you can add the new Font Awesome version in your custom.css
> @import url("https://use.fontawesome.com/releases/v5.3.1/css/all.css");
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/glitch452/MMM-LocalTemperature/issues/15#issuecomment-808939864", "url": "https://github.com/glitch452/MMM-LocalTemperature/issues/15#issuecomment-808939864", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by hxreborn** [comment]
> Hi Rafagale,   I hope you are fine. Sorry to bother you but where do I find the custom.css ?  
 Thanks for your help   
Cheers  
 Yann   


Hi, no problem. You have to create a file named **custom.css** inside MagicMirror/css/ directory, at the same level as the main.css

with the following content:

`@import url("https://use.fontawesome.com/releases/v5.3.1/css/all.css");`

**Comment by lunaticasylum** [comment]
Hi Rafagale,

 

I did not have time to do it. I have just tried and it works perfectly. You are a genius !!

 

I wish you a good evening or good morning depending where you live ;)

 

Yann

 

 

 

 

> Message du 25/04/21 21:26
> De : "rafagale" 
> A : "glitch452/MMM-LocalTemperature" 
> Copie à : "lunaticasylum" , "Mention" 
> Objet : Re: [glitch452/MMM-LocalTemperature] Square icon instead of the temperature icon (#15)
> 
>
>


> Hi Rafagale,   I hope you are fine. Sorry to bother you but where do I find the custom.css ?  
> Thanks for your help  
> Cheers  
> Yann  


> Hi, no problem. You have to create a file named custom.css inside MagicMirror/css/ directory, at the same level as the main.css

> with the following content:

> @import url("https://use.fontawesome.com/releases/v5.3.1/css/all.css");

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/glitch452/MMM-LocalTemperature/issues/15#issuecomment-826376691", "url": "https://github.com/glitch452/MMM-LocalTemperature/issues/15#issuecomment-826376691", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
