### ISSUE TITLE
Conflict with PIR Sensor

### ISSUE THREAD

**Issue by treeswoodhead** [glitch452/MMM-LocalTemperature#18]
Sensor not reading when PIR sensor connected each one works separate any ideas.

**Comment by glitch452** [comment]
Hi, Unfortunately I don't really know what could be wrong with your setup.  Make sure there are no GPIO pin conflicts and that the PIR sensor is not blocking the pin for the temperature sensor when it's active.  Also, there were a couple updates in v1.4.0, so you could try that and make sure to update wiringpi to the latest version if using a Pi4b.
