### ISSUE TITLE
The module not show

### ISSUE THREAD

**Issue by zoldev** [glitch452/MMM-LocalTemperature#23]
I installed the module but when i added in the config.js file, the module is not show on screen. No error messages, just not show the module.
Why?
Please help me.

I found an error in developer tools:

Uncaught SyntaxError: Identifier 'config' has already been declared
    at MMM-LocalTemperature.js:1

I installed the version 1.1.0
This is WORKS FINE!

**Comment by glitch452** [comment]
Hi, unfortunately I can't reproduce the problem.

**Comment by przypieczony** [comment]
Same on my side. I have installed the latest version of MagicMirror yesterday

**Comment by glitch452** [comment]
By default, the module does not show anything on the display, it's primarily intended to send the temperature and humidity values to the built-in weather module to be displayed.  Check your config to make sure the weather module is set to display those values, or set the inputs on this module to display the values.
