### ISSUE TITLE
Module not displaying data from DHT-22

### ISSUE THREAD

**Issue by CyberRagz** [glitch452/MMM-LocalTemperature#25]
My MM was working fine till recently when i had to reinstall everything. I could recover all my modules in the new install, except Local Temperature module. My sensor is connected to the pi and i was able to check the voltage on the pins of the DHT-22 which is okay. The module was installed as per steps in the Github page and configured correctly in the config.js file.
The npm start logs do not show any error, but the data is not displayed.
Any pointers to how to go ahead to resolve the issue.
Thanks

**Comment by AchMol** [comment]
Hello,

same here, DHT is fetching the temperature and humidity on the shell and there are no errors during loading the module. But the modul is not visible in the browser and the data is not shown at all (DHT-22, RPI4B).

**Comment by glitch452** [comment]
Hi, Please check your config. By default this module does not display anything, it sends the data to the weather module to be displayed, but you can enable that.  Also, there may be an issue with needing to use or not use sudo when the module runs the command.  I recently added an option to choose whether or not to use sudo, so make sure to update then give both a try and see.

**Comment by AchMol** [comment]
Hi glitch452, thanks for the quick replay.
I thought I testet all combination:

{
                        module: "MMM-LocalTemperature",
                        position: "top_left",
                        header: "Room Temperature",
                        config: {
                                sensorPin: 0, // For GPIO 17,
                                pinScheme: "WPI",
                                useSudo: true,
                                IconView: true,
                                showTemperature: true,
                                showHumidity: true,
                                sendTemperature: true,
                                sendHumidity: true,
                                updateInterval: 3,
                                initialLoadDelay: 0,
                                retryDelay: 3,
                                }
                },

and also
                                module: "weather",
                                [...]
                                showIndoorTemperature: true,
                                showIndoorHumidity: true,
                                [...]

What can be wrong? Call the DHT file on the shell delivers

root@raspberrypi:/opt/MagicMirror/modules/MMM-LocalTemperature# ./DHT 0 -m j 
{ "humidity": 52.2, "celcius": 19.3, "fahrenheit": 66.7, "kelvin": 292.4, "attempts": 5 }

**Comment by AchMol** [comment]
Hello,
we can close this one. Didn't find any error but couldn't make it work. I switched to MMM-loldht22.
Thanks,
Achmo
