### ISSUE TITLE
How to read the sensor data on the new Raspberry Pi 4

### ISSUE THREAD

**Issue by guzand3r** [glitch452/MMM-LocalTemperature#5]
Hello,

first, thanks for this module ! 

i've trouble with DHT executable, it works perfectly when i type ./DHT 16 c h (for example) i get two good values but when i execute it with sudo it can't retrieve data (error like there wasn't DHT captor connected). So as DHT is launched in MM with sudo (i seen that in developper mode in MM) no values are displayed on it.

How can i do for it works with sudo ? or launched it without sudo ?

Thanks to help me, i'm on this trouble since 10-15 hours and i tried everything and it don't still work, i'm sure i'm so close, it's frustating !

(it's my first post on github so apologize if redaction rules are not conform)

**Comment by guzand3r** [comment]
I used Pi4, so i have to upgrade WiringPI to 2.52 version

**Comment by BoraSchninsky** [comment]
Don't close.  Please answer the solution please..
Because other guys will have a answer.
Thanks

guzand3r <notifications@github.com> schrieb am Fr., 5. Juli 2019 05:05:

**Comment by guzand3r** [comment]
For my MM I use Pi4, so i have to upgrade WiringPI to latest 2.52 version

Solution found here (obviously !) : http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/

cd /tmp
wget https://project-downloads.drogon.net/wiringpi-latest.deb
sudo dpkg -i wiringpi-latest.deb

now it works perfectly, finaly !

**Comment by glitch452** [comment]
Closing... The readme has been updated to include pi4 instructions for updating wiringpi.
