### ISSUE TITLE
feature request: degreeLabel

### ISSUE THREAD

**Issue by GattoJohnny** [glitch452/MMM-LocalTemperature#6]
Hey @glitch452 ,

First of all, thank you very much for this awesome module. I've been using it since my first MM installation. And it works like charm.

As far as I understood there are two ways of displaying the data. Either icons + unit symbol (Celsius in my case), or any formatted text but icons. However, I'd like to use icons in the module, without the Celsius symbol. I wonder if you could implement the same parameter as it works in _Current Weather_.

Or is there a workaround now?

**Comment by glitch452** [comment]
Hello,

Thanks for the positive feedback.

There was no way to do what you were asking in the current implementation, so I've created a new release which includes the ability to use icons in the temperatureText and humidityText strings.  I think this gives the wides range of flexibility.  

So... If you wanted to use the icon with the temperature value and no temperature unit you can update to the latest version of the module and use the following configuration options:
```js
{
    sensorPin: <int>,
    iconView: false,
    showTemperature: true,
    temperatureText: "{icon-thermometer-half} {temperature}"
}
```

See the [README.md](https://github.com/glitch452/MMM-LocalTemperature) for a few more details on using icons in the temperatureText and humidityText strings.

**Comment by GattoJohnny** [comment]
Thank you for the enhancement in such a quick turnaround. 

Now both values are shown as I wanted them to look, except the extra line break. Can I make them one line again as it used to be?

I noticed that the _humidityText_ description refers to the _thermometer-half_ icon as an example. You may want to change it to _tint_.

**Comment by GattoJohnny** [comment]
Ooooooops, I cheated by specifying 
`temperatureText: "{icon-thermometer-half} {temperature}° {icon-tint} {humidity}%",`

Although it's not too elegant, but it works. Please let me know if there's a more proper way.

**Comment by glitch452** [comment]
Haha, actually, that was what I was going to recommend. I intentionally allowed the humidity and temperature values to be used in either string, for maximum flexibility. You can think of temperatureText and humidityText as labels that describe the intended use, but really it’s just line1 and line2.
