### ISSUE TITLE
Feature request: Temperature offset

### ISSUE THREAD

**Issue by PhilGrueAlt** [glitch452/MMM-LocalTemperature#8]
Hi,
first of all, I'd like to thank you for this awesome module! It's a really nice enhancement for my mirror! Unfortunetly, my DHT22 does not provide exact temperature values. The temperature shown is normally +1-1,5°C above the real temperature (checked with different thermometers). Therefore, a simple offset value (set in the module config) would be nice to fix this inaccuracy.
Maybe you can add this feature in an upcoming release! I'd be happy!

**Comment by glitch452** [comment]
Hi, This is definitely a good idea.  I'll get it into the next release.  Thanks for the input!

**Comment by erikvoznak** [comment]
Hello, when do you plan next release with offset? I see that you committed last update almost half year ago. because I would also welcome such option as my sensor is approx 1.5 - 2C above real temp. maybe is there any option how to calibrate sensor itself?

**Comment by glitch452** [comment]
I'm going to try to get to it this week.  If not, then in the next few weeks... Should be a quick update though.  But yeah, this module is fairly low maintenance and has been working well for me, so I haven't had to make and updates in a while.

**Comment by Exezz78** [comment]
Great idea on the offset! +1

**Comment by 2hdlockness** [comment]
> Hi, This is definitely a good idea. I'll get it into the next release. Thanks for the input!

Hello
Is this enhancement still planned?
Thank you for your reply.

**Comment by glitch452** [comment]
Added in v1.4.0.  Sorry for taking so long!
