### ISSUE TITLE
thermometer icon disappeared

### ISSUE THREAD

**Issue by rubenix** [glitch452/MMM-LocalTemperature#9]
Hello, im using this beauty module and somehow the thermometer icon is not there anymore.
started from scratch but could not solve the issue.
is there something I can try?
humidity icon it shows as usual
thanks!

**Comment by rubenix** [comment]
Solution I found: MMM-LocalTemperature.js  line 330 --> fas fa-thermometer-half
Something changed on FA

**Comment by glitch452** [comment]
I'll look into this and if needed, I'll include a fix in the next release.  Thanks for the feedback!

**Comment by Ponguipaple** [comment]
Hi all,
I just tried and can confirm your solution works just fine.
I am also going to try it on MMM-SystemStats as some icons also disappeared... Maybe same reason.

**Comment by glitch452** [comment]
So, after testing on the latest version of MagicMirror, I don't see an issue with the thermometer loading, so I'll leave it as is for now.
